SELECT * FROM STUDENTS;
SELECT * FROM COURSES;
SELECT * FROM ENROLLEMENTS;
SELECT * FROM STUDENTS WHERE student_name NOT LIKE '%REDDY%';
SELECT age ,COUNT(*) FROM STUDENTS GROUP BY age HAVING COUNT(age)>1;
UPDATE ENROLLEMENTS SET enroll_timestamp=SYSDATETIME() WHERE enroll_id=11101;
SELECT * FROM ENROLLEMENTS ORDER BY enroll_timestamp ASC;