USE collegedatabase;
SELECT * FROM STUDENTS WHERE age>21;
SELECT * FROM STUDENTS WHERE active_flag=1;
SELECT * FROM COURSES WHERE fees BETWEEN 1000 AND 5000;
SELECT * FROM STUDENTS WHERE age IN (20,22,25);

SELECT * FROM STUDENTS WHERE age>20 AND active_flag=1;
SELECT * FROM STUDENTS WHERE age<20 OR active_flag=0;
SELECT * FROM COURSES WHERE fees>2000 AND course_name LIKE '%SCIENCE%';


SELECT * FROM STUDENTS WHERE email LIKE '%gmail.com';
SELECT * FROM COURSES WHERE course_name LIKE 'DATA%';


INSERT INTO STUDENTS VALUES(112334,'SUSHANTH','SAINANIREDDY20@GMAIL.COM',NULL,'2026-05-01',0,NULL);
SELECT * FROM STUDENTS WHERE age IS NULL;
SELECT * FROM STUDENTS WHERE age IS NOT NULL;