USE collegedatabase;
CREATE TABLE STUDENTS(student_id BIGINT PRIMARY KEY, student_name VARCHAR(50),
email VARCHAR(50) UNIQUE,age INT,join_date DATE,active_flag BIT DEFAULT 1);
CREATE TABLE COURSES(course_id INT PRIMARY KEY, course_name VARCHAR(50) NOT NULL,
fees DECIMAL);
CREATE TABLE ENROLLEMENTS(enroll_id BIGINT PRIMARY KEY, student_id BIGINT,
course_id INT,enroll_timestamp TIMESTAMP);
DROP TABLE ENROLLEMENTS;
CREATE TABLE ENROLLEMENTS(enroll_id BIGINT PRIMARY KEY, student_id BIGINT,
course_id INT,enroll_timestamp DATETIME DEFAULT GETDATE());




ALTER TABLE ENROLLEMENTS
DROP CONSTRAINT DF__ENROLLEME__enrol__3F466844;


ALTER TABLE ENROLLEMENTS
DROP COLUMN enroll_timestamp;

ALTER TABLE ENROLLEMENTS
ADD enroll_timestamp DATETIME2 DEFAULT SYSDATETIME();


ALTER TABLE ENROLLEMENTS
ALTER COLUMN enroll_timestamp DATETIME2 DEFAULT SYSDATETIME();

