SELECT COUNT(CASE WHEN age>20 THEN 1 ELSE NULL END) FROM STUDENTS;
SELECT COUNT(CASE WHEN student_name LIKE '%A%' THEN 1 ELSE NULL END) FROM STUDENTS;
SELECT * FROM COURSES WHERE fees BETWEEN 1000 AND 5000  ORDER BY fees DESC;
SELECT * FROM STUDENTS WHERE active_flag=0 AND age IS NOT NULL;
SELECT student_id ,COUNT(*) no_of_courses FROM ENROLLEMENTS GROUP BY student_id HAVING COUNT(*)>0; 